---
- name: Playbook to view NTP sync status
  hosts: cisco_ios
  gather_facts: no
  connection: network_cli

  tasks:

  - name: Running command
    ios_command:
       commands:
        - show ntp associations 

    register: output

  - debug:
      var: output.stdout
