---
- name: Playbook to view NTP config
  hosts: cisco_ios
  gather_facts: no
  connection: network_cli

  tasks:

  - name: Checking config
    ios_command:
       commands:
        - "show running-config | include clock timezone"
        - "show running-config | include clock summer-time"
        - "show running-config | include ntp source"
        - "show running-config | include ntp server"
        - "show running-config | include ntp access-group"
    register: output

  - debug:
      var: output.stdout
