---
- name: Playbook to view NTP sync status
  hosts: nxos
  gather_facts: no
  connection: local

  tasks:

  - name: Running command
    nxos_command:
       commands:
        - show ntp peer-status
    register: output

  - debug:
      var: output.stdout
