---
- name: NXOS Facts Playbook
  hosts: nxos
  gather_facts: false
  connection: network_cli

  tasks:

  - name: Checking device information
    nxos_facts:
       gather_subset: hardware
    
    register: facts
  - name: Display facts
    debug:
      var: facts

