---
- name: Playbook to backup running config of Cisco NXOS device
  hosts: nxos
  gather_facts: no
  connection: network_cli

  tasks:
     - name: Backing up Running Config into playbook directory
       nxos_config:
         backup: yes
         backup_options:
           filename: "{{ inventory_hostname }}-{{ lookup('pipe', 'date +%Y%m%d-%H-%M') }}_running-config.cfg"
           dir_path: ./
        
