---
- name: Playbook to check ACL on Cisco NXOS devices
  hosts: nxos
  gather_facts: no
  connection: network_cli

  tasks:

  - name: Checking ACL configuration
    nxos_command:
      commands:
        - show access-lists
    register: output

  - debug:
      var: output.stdout
