---
- name: Playbook to view CPU usage on Cisco NXOS devices
  hosts: nxos
  gather_facts: no
  connection: network_cli

  tasks:

  - name: Running "show cpu process" command
    nxos_command:
      commands:
        - show processes cpu sort  | i CPU
    register: output

  - debug:
      var: output.stdout
